<?php

namespace Kitano\ConnectionBundle\Entity;

use Kitano\ConnectionBundle\Model\Connection as ConnectionBase;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Connection extends ConnectionBase
{
}
