<?php

namespace Kitano\ConnectionBundle\Repository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineMondoDbConnectionRepository implements ConnectionRepositoryInterface
{
    // TODO: implement
}
